### ISSUE TITLE
Define Requirements and user stories.

### ISSUE THREAD

**Issue by tfadeyi** [comp6239/Personal-tutor-finder-app#10]

**Comment by Cecish** [comment]
I've written the requirements and drawn the use case diagram. Could you please review these (especially the bits with comments) when you have time?

**Comment by tfadeyi** [comment]
I'll have a look at it tomorrow morning :+1:

**Comment by tfadeyi** [comment]
I totally ok with the use case diagram :+1: .
I'll finish the subject pkg module today and add getUserInstance() to the userManager so we can have different main activities depending on the role.

**Comment by tfadeyi** [comment]
Also great work on the requirements :100: , sorry I wasn't much help there...
