### ISSUE TITLE
View/Edit user profile

### ISSUE THREAD

**Issue by tfadeyi** [comp6239/Personal-tutor-finder-app#11]
Registered users of the app can create their profile and complete their learning needs if they are students, or in case of tutors, users can complete their profile with their skills list (subject list).

This simply must allow users to add different subjects (such as Physics, Maths, Music, etc.) to their respective lists.

**Comment by Cecish** [comment]
Requires #4

**Comment by Cecish** [comment]
TODO:
1) Complete edit profile (load/save subjects)
2) Make the back button work
3) Make sure that when a user edits his profile and goes back to the previous activity (view profile), his profile in view mode is updated
