### ISSUE TITLE
Forgot Password Flow

### ISSUE THREAD

**Issue by tfadeyi** [comp6239/Personal-tutor-finder-app#21]
The forgot password still needs to be handled.

**Comment by Cecish** [comment]
I am struggling to enable the password reset to occur within the app. Tried to follow this: https://firebase.google.com/docs/auth/web/passing-state-in- #email-actions, but stuck at "Receiving Android Dynamic Links instructions". Is resetting the password outside the app enough?
 ##
Also, we've not discussed this but should we add an app bar with a up button? #

**Comment by tfadeyi** [comment]
@Cecish The password reset outside the app is fine, we can always come back to it later.
I think we should have an up button in the app bar, but I really don't remember how to specify it, I think it was in the manifest.
