### ISSUE TITLE
Add MainActivity

### ISSUE THREAD

**Issue by tfadeyi** [comp6239/Personal-tutor-finder-app#4]
Add main activity for the home screen of the application.

**Comment by tfadeyi** [comment]
Just a skeleton, not a complete activity.

**Comment by tfadeyi** [comment]
Have different activity depending on the user role

**Comment by tfadeyi** [comment]
Main Activity should display upcoming sessions and number of new messages received.

**Comment by Cecish** [comment]
N upcoming sessions (N can be parametrised) are now displayed in the main activity of students and tutors
